---
apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  name: k8s-readonly-server
  namespace: agent-team
  labels:
    kagenti.io/type: tool
    kagenti.io/tool-protocol: mcp
spec:
  type: tool
  description: "Kubernetes read-only MCP server for cluster introspection"
  suspend: false

  # Build from source using Tekton
  agent:
    build:
      mode: dev
      pipeline:
        namespace: ""
        parameters:
        - name: SOURCE_REPO_SECRET
          value: github-token-secret
        - name: repo-url
          value: github.com/usize/a2a-cluster-bridge
        - name: revision
          value: main
        - name: subfolder-path
          value: servers/k8s-readonly-server
        - name: image
          value: image-registry.openshift-image-registry.svc:5000/agent-team/k8s-readonly-server:latest
        steps:
        - configMap: github-clone-step
          enabled: true
          name: github-clone
        - configMap: check-subfolder-step
          enabled: true
          name: folder-verification
        - configMap: kaniko-docker-build-step
          enabled: true
          name: kaniko-build

  # Deploy after build completes
  deployer:
    deployAfterBuild: true
    name: k8s-readonly-server
    namespace: agent-team
    env:
    - name: MCP_SERVER_PORT
      value: "8080"
    - name: ALLOWED_NAMESPACES
      value: "agent-team,kagenti-system"
    kubernetes:
      serviceAccountName: k8s-readonly-server
      containerPorts:
      - containerPort: 8080
        name: mcp
        protocol: TCP
      imageSpec:
        image: k8s-readonly-server
        imagePullPolicy: Always
        imageRegistry: image-registry.openshift-image-registry.svc:5000/agent-team
        imageTag: latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      servicePorts:
      - name: mcp
        port: 8080
        protocol: TCP
        targetPort: 8080
